import type { SymptomDefinition } from "./types.ts";

export const symptomCatalog: SymptomDefinition[] = [
  { id: "skin-urticaria", name: "Крапивница", system: "skin", subgrade: "light" },
  { id: "skin-erythema", name: "Эритема", system: "skin", subgrade: "light" },
  { id: "skin-itching", name: "Зуд", system: "skin", subgrade: "light" },
  { id: "skin-discomfort", name: "Дискомфорт кожи", system: "skin", subgrade: "light" },
  { id: "skin-tingling", name: "Генерализованное чувство покалывания", system: "skin", subgrade: "light" },
  { id: "skin-excoriation", name: "Экскориации", system: "skin", subgrade: "light" },
  { id: "skin-angioedema", name: "АНО вне слизистых", system: "skin", subgrade: "moderate" },

  { id: "mucous-conjunctivitis", name: "Конъюнктивит", system: "mucous", subgrade: "light" },
  { id: "mucous-chemosis", name: "Хемоз", system: "mucous", subgrade: "light" },
  { id: "mucous-eye-itch", name: "Внезапный зуд глаз", system: "mucous", subgrade: "light" },
  { id: "mucous-eyelid", name: "Отёк век", system: "mucous", subgrade: "light" },
  { id: "mucous-throat", name: "Дискомфорт, зуд, першение, боль или «ком» в горле", system: "mucous", subgrade: "light" },
  { id: "mucous-oas", name: "ОАС: зуд, покалывание, металлический привкус во рту", system: "mucous", subgrade: "light" },
  { id: "mucous-swallow", name: "Нарушение глотания", system: "mucous", subgrade: "light" },
  { id: "mucous-nasal", name: "Заложенность носа", system: "mucous", subgrade: "light" },
  { id: "mucous-rhinorrhea", name: "Ринорея", system: "mucous", subgrade: "light" },
  { id: "mucous-sneeze", name: "Чихание", system: "mucous", subgrade: "light" },
  { id: "mucous-lips", name: "Отёк губ", system: "mucous", subgrade: "moderate" },
  { id: "mucous-salivation", name: "Появление или усиление слюнотечения", system: "mucous", subgrade: "moderate" },
  { id: "mucous-tongue", name: "Отёк языка, мягкого нёба, язычка", system: "mucous", subgrade: "severe" },

  { id: "gi-pain-light", name: "Боль в животе — эпизодическая", system: "gastrointestinal", subgrade: "light" },
  { id: "gi-pain", name: "Боль в животе — постоянная, сильная", system: "gastrointestinal", subgrade: "moderate" },
  { id: "gi-nausea-light", name: "Тошнота — эпизодическая", system: "gastrointestinal", subgrade: "light" },
  { id: "gi-nausea", name: "Тошнота — постоянная", system: "gastrointestinal", subgrade: "moderate" },
  { id: "gi-vomit-light", name: "Рвота — 1–2 раза", system: "gastrointestinal", subgrade: "light" },
  { id: "gi-vomit", name: "Рвота — более 2 раз", system: "gastrointestinal", subgrade: "moderate" },
  { id: "gi-diarrhea-light", name: "Диарея — 1–2 раза", system: "gastrointestinal", subgrade: "light" },
  { id: "gi-diarrhea", name: "Диарея — более 2 раз", system: "gastrointestinal", subgrade: "moderate" },
  { id: "gi-infant", name: "У младенца: икота, выгибание спины, срыгивание", system: "gastrointestinal", subgrade: "light" },

  { id: "cv-tachycardia", name: "Тахикардия", system: "cardiovascular", subgrade: "light" },
  { id: "cv-pallor", name: "Бледность", system: "cardiovascular", subgrade: "light" },
  { id: "cv-weakness", name: "Слабость, вялость", system: "cardiovascular", subgrade: "light" },
  { id: "cv-dizziness", name: "Головокружение", system: "cardiovascular", subgrade: "light" },
  { id: "cv-presyncope", name: "Предобморочное состояние", system: "cardiovascular", subgrade: "light" },
  { id: "cv-bradycardia", name: "Брадикардия", system: "cardiovascular", subgrade: "moderate" },
  { id: "cv-hypotension", name: "Гипотензия", system: "cardiovascular", subgrade: "moderate" },
  { id: "cv-cyanosis", name: "Цианоз", system: "cardiovascular", subgrade: "moderate" },
  { id: "cv-capillary", name: "Симптом бледного пятна более 3 сек", system: "cardiovascular", subgrade: "moderate" },
  { id: "cv-collapse", name: "Коллапс", system: "cardiovascular", subgrade: "severe" },
  { id: "cv-arrest", name: "Остановка сердца", system: "cardiovascular", subgrade: "severe" },
  { id: "cv-shock", name: "Анафилактический шок", system: "cardiovascular", subgrade: "severe" },

  { id: "neuro-confusion", name: "Спутанность сознания", system: "neurological", subgrade: "light" },
  { id: "neuro-anxiety", name: "Чувство тревоги, страх смерти", system: "neurological", subgrade: "light" },
  { id: "neuro-sleepy", name: "Сонливость, летаргия", system: "neurological", subgrade: "light" },
  { id: "neuro-agitation", name: "Возбуждение, раздражительность, безутешность", system: "neurological", subgrade: "light" },
  { id: "neuro-infant", name: "Снижение активности у младенца", system: "neurological", subgrade: "moderate" },
  { id: "neuro-seizure", name: "Судороги", system: "neurological", subgrade: "severe" },
  { id: "neuro-hypotonia", name: "Снижение мышечного тонуса, «обмякание»", system: "neurological", subgrade: "severe" },
  { id: "neuro-syncope", name: "Обморок", system: "neurological", subgrade: "severe" },
  { id: "neuro-incontinence-urine", name: "Недержание мочи", system: "neurological", subgrade: "severe" },
  { id: "neuro-incontinence-fecal", name: "Недержание кала", system: "neurological", subgrade: "severe" },

  { id: "resp-inhale", name: "Затруднение вдоха", system: "respiratory", subgrade: "light" },
  { id: "resp-exhale", name: "Затруднение выдоха", system: "respiratory", subgrade: "light" },
  { id: "resp-tightness", name: "Чувство стеснения в груди", system: "respiratory", subgrade: "light" },
  { id: "resp-dysphonia", name: "Дисфония", system: "respiratory", subgrade: "light" },
  { id: "resp-barking", name: "Лающий кашель", system: "respiratory", subgrade: "light" },
  { id: "resp-new-cough", name: "Появление кашля", system: "respiratory", subgrade: "light" },
  { id: "resp-dyspnea", name: "Одышка без ПРД", system: "respiratory", subgrade: "light" },
  { id: "resp-stridor", name: "Стридор без ПРД", system: "respiratory", subgrade: "moderate" },
  { id: "resp-wheeze", name: "Дистанционные хрипы", system: "respiratory", subgrade: "moderate" },
  { id: "resp-work", name: "Работа вспомогательной мускулатуры", system: "respiratory", subgrade: "moderate" },
  { id: "resp-flaring", name: "Раздувание крыльев носа", system: "respiratory", subgrade: "moderate" },
  { id: "resp-persistent", name: "Кашель персистирующий", system: "respiratory", subgrade: "moderate" },
  { id: "resp-stridor-prd", name: "Стридор с ПРД", system: "respiratory", subgrade: "severe" },
  { id: "resp-silent", name: "Одышка с ДН, «немое лёгкое»", system: "respiratory", subgrade: "severe" },
  { id: "resp-failure", name: "Дыхательная недостаточность, требуется O₂", system: "respiratory", subgrade: "severe" },
];
